<?php
/**
 * Custom Bootstrap3 template - yourcar.co.nz
 */
?>
<!DOCTYPE HTML>
<html>
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
        <?php echo $this->getChildHtml('after_body_start') ?>
<header> 
        <?php echo $this->getChildHtml('header') ?>
</header>
<main>
    <section id="maincontent">
        <div class="container">
            <div class="row">
                <?php echo $this->getChildHtml('breadcrumbs') ?>            
                <div class="col-main col-md-8">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                </div>
                <aside class="col-right sidebar col-md-4">
                        <?php echo $this->getChildHtml('right') ?>
                </aside>
            </div>
        </div>
    </section>
</main>    
<footer id="footer">
    <div class="container">
         <?php echo $this->getChildHtml('footer') ?>
    </div>
</footer>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
